"""Builds the globe's bundled geography from Natural Earth (public domain):

    mcc/web/world.js     land as a dot grid + simplified coastlines, base64-packed Int16 arrays
    mcc/geodata.py       country code -> (lat, lon, name) label points, for country-level databases

    python tools/build_world.py <ne_110m_land.geojson> <ne_110m_admin_0_countries.geojson>

Source: https://github.com/nvkelso/natural-earth-vector (geojson/ne_110m_*.geojson).
Only needed when regenerating; the outputs are committed.
"""

from __future__ import annotations

import base64
import json
import math
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STEP = 1.5  # degrees between land dots (latitude; longitude is widened toward the poles)


def rings(geom):
    if geom["type"] == "Polygon":
        return [geom["coordinates"]]
    if geom["type"] == "MultiPolygon":
        return geom["coordinates"]
    return []


def inside(x, y, ring):
    c = False
    j = len(ring) - 1
    for i in range(len(ring)):
        xi, yi = ring[i][0], ring[i][1]
        xj, yj = ring[j][0], ring[j][1]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi + 1e-12) + xi:
            c = not c
        j = i
    return c


def simplify(pts, tol):
    if len(pts) < 4:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        ax, ay = pts[a]
        bx, by = pts[b]
        dx, dy = bx - ax, by - ay
        norm = math.hypot(dx, dy) or 1e-12
        best, idx = 0.0, -1
        for i in range(a + 1, b):
            d = abs(dy * pts[i][0] - dx * pts[i][1] + bx * ay - by * ax) / norm
            if d > best:
                best, idx = d, i
        if best > tol and idx > 0:
            keep[idx] = True
            stack += [(a, idx), (idx, b)]
    return [p for p, k in zip(pts, keep) if k]


def main(land_path, countries_path):
    land = json.loads(Path(land_path).read_text(encoding="utf-8"))
    polys = []
    for f in land["features"]:
        for poly in rings(f["geometry"]):
            outer = poly[0]
            xs = [p[0] for p in outer]
            ys = [p[1] for p in outer]
            polys.append((min(xs), max(xs), min(ys), max(ys), poly))

    dots = []
    lat = -88.5
    while lat <= 88.5:
        step_lon = STEP / max(0.15, math.cos(math.radians(lat)))
        lon = -180.0 + (step_lon / 2 if int((lat + 90) / STEP) % 2 else 0)
        while lon < 180.0:
            for x0, x1, y0, y1, poly in polys:
                if x0 <= lon <= x1 and y0 <= lat <= y1 and inside(lon, lat, poly[0]) and \
                        not any(inside(lon, lat, hole) for hole in poly[1:]):
                    dots.append((lat, lon))
                    break
            lon += step_lon
        lat += STEP

    coast = []
    for *_bbox, poly in polys:
        ring = [(p[0], p[1]) for p in poly[0]]
        # a closed ring starts and ends on the same point: split it at the farthest point first
        far = max(range(len(ring)), key=lambda i: math.hypot(ring[i][0] - ring[0][0], ring[i][1] - ring[0][1]))
        pts = simplify(ring[:far + 1], 0.25) + simplify(ring[far:], 0.25)[1:]
        if len(pts) >= 4:
            coast.append(pts)

    dot_bytes = b"".join(struct.pack("<hh", round(la * 100), round(lo * 100)) for la, lo in dots)
    coast_bytes = b""
    for ring in coast:
        coast_bytes += b"".join(struct.pack("<hh", round(y * 100), round(x * 100)) for x, y in ring)
        coast_bytes += struct.pack("<hh", 32767, 32767)  # ring separator
    js = ("/* Generated by tools/build_world.py from Natural Earth 1:110m land (public domain). */\n"
          "\"use strict\";\nwindow.WORLD = {\n  dots: \"%s\",\n  coast: \"%s\"\n};\n"
          % (base64.b64encode(dot_bytes).decode(), base64.b64encode(coast_bytes).decode()))
    (ROOT / "mcc" / "web" / "world.js").write_text(js, encoding="utf-8")

    countries = json.loads(Path(countries_path).read_text(encoding="utf-8"))
    cents = {}
    for f in countries["features"]:
        p = f["properties"]
        cc = p.get("ISO_A2_EH") or p.get("ISO_A2")
        if not cc or cc == "-99" or len(cc) != 2:
            continue
        lat_c, lon_c = p.get("LABEL_Y"), p.get("LABEL_X")
        if lat_c is None or lon_c is None:
            continue
        cents[cc] = (round(lat_c, 2), round(lon_c, 2), p.get("NAME") or cc)
    lines = ["\"\"\"Country label points from Natural Earth 1:110m admin-0 (public domain).",
             "Generated by tools/build_world.py -- used to place country-level geolocation results.\"\"\"", "",
             "CENTROIDS = {"]
    for cc in sorted(cents):
        la, lo, name = cents[cc]
        lines.append("    {!r}: ({}, {}, {!r}),".format(cc, la, lo, name))
    lines.append("}")
    (ROOT / "mcc" / "geodata.py").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("dots: {}  coast rings: {} ({} pts)  countries: {}  world.js: {:.0f} KB".format(
        len(dots), len(coast), sum(len(r) for r in coast), len(cents),
        len(js) / 1024))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
